Quadro de conhecimentos
fga-eps-mds/2024-1-GEROcuidado-Doc pull request #18
Opened 2024-04-07 13:52 UTC by sebazac332

## Descrição
Criada a página de quadro de conhecimentos e adicionados os quadros de conhecimentos gerais e quadros de sprint 1 e sprint 2.
## Issue
Closes #9

## Tipos de Mudanças
 - [ ] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [x] Documentação

2024-04-09 15:57 UTC, AmandaNbr requested changes

2024-04-09 15:57 UTC, AmandaNbr commented on mkdocs.yml
> +    - Quadro de conhecimento: planejamento/quadro_de_conhecimentos.md
Colocar o Quadro de conhecimento abaixo do quadro de disponibilidade!

2024-04-10 15:05 UTC, sebazac332 commented on mkdocs.yml
> +    - Quadro de conhecimento: planejamento/quadro_de_conhecimentos.md
Feito

2024-04-11 03:36 UTC, AmandaNbr approved these changes

2024-04-11 03:36 UTC, merged